use_frameworks!

platform :ios, '10.0'

target 'SFCircleProgressView_Example' do
  pod 'SFCircleProgressView', :path => '../'

  target 'SFCircleProgressView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
